### ISSUE TITLE
Add Value Aware Exception

### ISSUE THREAD

**Issue by XedinUnknown** [Dhii/exception-interface#4]
There are multiple types of exception that are caused by erroneous, incorrect, or invalid values. Examples include [`OutOfBoundsException`], [`OutOfRangeException`], [`TypeError`], [`ValidationFailedExceptionInterface`] and potentially many others. Whatever value causes that kind of exception, one thing is in common: the value. However, there does not appear to be a way, much less a uniform way, of retrieving that value from the exception.

This calls for a unifying exception interface, which would allow the retrieval of the value that caused it. The only question that remains is how to name it in such as way that would most generically yet accurately describe its purpose.

1. `ValueAwareExceptionInterface` - This could extend [`ValueAwareInterface`]. However, traditionally this interface is used by objects that **represent** a value.
2. `SubjectAwareExceptionInterface` - This sounds like a good alternative to [`ValueAwareInterface`], as it allows distinguishing the wrong value associated with the instance from the value that it may represent.  This could tie in nicely with [`ValidationFailedExceptionInterface`].
3. `BadValueExceptionInterface` - Very semantically correct, generic and precise. However, suggests extending [`ValueAwareInterface`] - see point 1.

[`OutOfBoundsException`]: http://php.net/manual/en/class.outofboundsexception.php
[`OutOfRangeException`]: http://php.net/manual/en/class.outofrangeexception.php
[`TypeError`]: http://php.net/manual/en/class.typeerror.php
[`ValidationFailedExceptionInterface`]: https://github.com/Dhii/validation-interface/blob/release/0.2/src/Exception/ValidationFailedExceptionInterface.php
[`ValueAwareInterface`]: https://github.com/Dhii/data-key-value-aware-interface/blob/master/src/ValueAwareInterface.php

**Comment by mecha** [comment]
Point 3 makes the most sense.

Regarding your concerns with [`ValueAwareInterface`](https://github.com/Dhii/data-key-value-aware-interface/blob/master/src/ValueAwareInterface.php), if you look at its doc you'll see that we've already been through this. Objects implementing this interface can represent **or** have a value. I see no problem in using it.

**Comment by XedinUnknown** [comment]
What about other exception interfaces that currently already expose their value via non-interop methods, such as `InvalidArgumentExceptionInterface#getArgument()`, `ValidationFailedExceptionInterface#getSubject()`?

**Comment by XedinUnknown** [comment]
@mecha, settled for `BadValueExceptionInterface`. This will introduce a BC-breaking change in `InvalidArgumentExceptionInterface` implementations. Do you remember if anything you did depends on it having a `getArgument()`?

**Comment by XedinUnknown** [comment]
I now realize that this is a bad idea. Example: you request a value by key that is not there. It is wrong to ask for key via `getValue()`, especially since both key and value may be wrong, but are this way indistinguishable.

**Comment by mecha** [comment]
@XedinUnknown If I recall, I've never depended on that method in my works.

**Comment by XedinUnknown** [comment]
So, do we agree on `BadSubjectExceptionInterface#getSubject()`?

**Comment by mecha** [comment]
Yes, I agree.

**Comment by XedinUnknown** [comment]
I just wanted to mention this. We thought of allowing the new interface to extend `ValueAwareInterface`, but decided against this. We said that it would be semantically confusing if you need to retrieve a key from it, because the bad value is a key. But IMHO the main reason why it can't extend `ValueAwareInterface` is that, although the interface is for "something that can represent or have a value", the value the exception _has_ is not **of** the exception. When something is allowed to **have** a value, it must be the value of **that** thing.

**Comment by XedinUnknown** [comment]
So, this is solved by adding a common `BadSubjectExceptionInterface`.
